---
title: "NURA Model"
output: html_notebook
---

```{r}
set.seed(123)
n = 100
X = cbind(Time=c(0), S=c(n), R=c(0)) # store output
l = 1 # birth rate
d = 0.5 # death rate
h = 0.01 # transformation rate
u1 = 0.01 # mutation rate of drug 1

# Update matrix for each event: faithful division, death, mutation, transformation.  
updateMatrix = matrix(c(1, 0,   -1,0,   0,1,   -1,1), nrow=4, ncol=2, byrow=TRUE)
updateMatrix
```


```{r}
i = 1 # row counter for matrix
# stochastic simulation algorithm
while(X[i, 3] < n * 0.1){
    rates = c(l*X[i, 2], d*X[i, 2], u1*X[i, 2], h*X[i, 2]) # indiv. event rates
    r = sum(rates) # total rate of some event happening
    tstep = rexp(1, r) # time to the next event
    
    p = rates/r # probability vector for each event type
    u = runif(1) # sample from standard uniform
    j = which(u <= cumsum(p)) [1] # sample which event occurred
    
    X = rbind(X, c(X[i, 1] + tstep, X[i, 2:3] + updateMatrix[j, ]))
    i = i + 1
}
```


```{r}
Time = X[, 1]
par(mfrow = c(1, 2))
plot(Time, X[, 2], ylab="S", ylim=c(0, sum(X[1, 2:3])), type="l", lwd=2)
plot(Time, X[, 3], ylab="R", ylim=c(0, sum(X[1, 2:3])), type="l", lwd=2)
```

